### ISSUE TITLE
Doesn't upload to non-existant folders / Doesn't create new folders.

### ISSUE THREAD

**Issue by VNRARA** [heminei/vscode-pro-deployer#11]
[2022-06-08T18:41:23.145Z][ERROR] xampp => Can't upload file: <dir-redacted>/components/db/func/data_functies.php. Details: Filename invalid

When I try to upload to a folder that doesn't exist in C:/Xampp it doesnt create a new folder. It just gives this error untill I manually create a folder.

**Comment by danzen** [comment]
Same here...

**Comment by heminei** [comment]
Hello, 
The bug is fixed on version 2.2.1
