### ISSUE TITLE
Download from site to local repository

### ISSUE THREAD

**Issue by AlexJMcloud** [heminei/vscode-pro-deployer#12]
I can rate everything related to uploading to FTP at 5. But, there is no reverse upload from the site.
I really hope this option is available.

And there will be a full-fledged deployer, as it exists in other editors.

**Comment by danzen** [comment]
Agreed - I have to go to other systems to do this.  Awkward.

**Comment by heminei** [comment]
Hi, I have released a new version 2.3.1. Now you can download or compare files.
