### ISSUE TITLE
Can't upload file : No such file or directory

### ISSUE THREAD

**Issue by briceparmentier** [heminei/vscode-pro-deployer#13]
Hi everyone,
I've tested some FTP addons to VS code, this one seems to be the easiest one to use for me.

I have an issue though, i can't upload a file I have just modified and I get the following error :
`[PRO Deployer] mhbot ftp => Can't upload file: /d:/my/dev/path/file.html. Details: Error: Can't open that file: No such file or directory`

The configuration I have is the auto generated one where I have only changed the credentials to my FTP server and the root path on it.

By reading the error message it seems like the extension is trying to search for a Linux path (leading slash at the beginning of the file path) while I'm on Windows.

Any idea?

**Comment by biffly** [comment]
Hi

I have the same problem, when I create a folder in VSCode the extension does not create the folder on the server, and when uploading a file it gives an error.

The extension works perfectly and is great, a great solution, it only lacks this last one.

Thanks a lot.

**Comment by heminei** [comment]
Hello, 
The bug is fixed on version 2.2.1

**Comment by biffly** [comment]
![image](https://github.com/heminei/vscode-pro-deployer/assets/8367673/de6003a4-2d85-47a9-803f-5bcca00db25f)
Create the "test" folder and inside it a "test.html" file, when saving it gives that error. It does not create the folder, if I enter through an FTP client and create the folder manually, the error no longer appears. The extension has problems creating directories.

![image](https://github.com/heminei/vscode-pro-deployer/assets/8367673/d20d42c2-f67f-43b8-a312-861061f17099)


I am currently using version 2.2.1

**Comment by heminei** [comment]
What do you set on the "dir" option in your target?

**Comment by biffly** [comment]
```
{
	"name": "dina",
	"type": "ftp",
	"host": "*************",
	"port": 21,
	"user": "******",
	"password": "*******",
	"dir": "/www/",
	"transferDataType": "binary"
}
```

**Comment by heminei** [comment]
I have checked on Windows and Linux. I don't have this problem. Also, I have tested with Linux and Windows FTP servers. Maybe you have a problem with FTP server permissions.

**Comment by biffly** [comment]
when I access by ftp I have no problem and using the extension everything works except creating a folder.  I don't think it's a permissions problem, I checked it.
