### ISSUE TITLE
How to Edit the Config...

### ISSUE THREAD

**Issue by danzen** [heminei/vscode-pro-deployer#15]
I am new to VS Code so it may just be me... but I did not see anywhere in your details as to how to edit an existing config nor where that config would be.  So I pressed generate a config and it seems to have overwritten my working config.  Sigh.  So some documentation on how to do that would be handy.  Cheers.

**Comment by danzen** [comment]
I see the file now... it is in a .vscode/pro-deployer.json directory....

**Comment by heminei** [comment]
Yes, the config file location is: `.vscode/pro-deployer.json`
