### ISSUE TITLE
New Tab in VS Code Status Bar for Quick Uploading and Status of Auto Uploading

### ISSUE THREAD

**Issue by a-kbv** [heminei/vscode-pro-deployer#17]
# Issue:

Integrate a new tab in the VS Code status bar with an "upload" or "reload" style similar to Copilot's functionality. This feature would enhance the user experience and improve the speed and convenience of uploading files.

# Description:

The proposed feature aims to add a new tab in the VS Code status bar that allows users to quickly upload files or reload changes made to the code. The idea is to emulate the style and functionality of Copilot, which provides users with an easy way to access different features or be notified about the extension actions without being annoyed

The new tab would be designed with an "upload" or "reload" style, similar to the GIF example provided, making it instantly recognizable and easy to use
![example](https://github.com/heminei/vscode-pro-deployer/assets/67587336/a1d1297e-17fe-41d3-83f3-248797ae8124)

**Comment by heminei** [comment]
Added in version 1.3.1
