### ISSUE TITLE
Limit asynchronous file uploads or add pause button to prevent crashes during bulk operations.

### ISSUE THREAD

**Issue by a-kbv** [heminei/vscode-pro-deployer#19]
I am experiencing an issue with the VS Code extension when "uploadOnSave" and "autoDelete" is enabled during bulk operations such as a `composer update`. With autosave enabled in VS Code, a large number of files are modified, and the extension attempts to upload thousands of files simultaneously. As a result, this causes the whole VS Code application to crash.

**Possible Solutions:**

1. Add a configuration option to limit async file uploads. This would allow users to set a threshold for simultaneous uploads, preventing crashes due to overwhelming the application with too many uploads at once.

2. Add a pause button for upload operations. Allowing users to temporarily pause uploading can ensure that bulk operations like `composer update` can complete without causing crashes. Currently, to pause uploading, users need to modify the config file and reload the VS Code IDE, which is not a convenient solution.

**Screenshots:**
![image](https://i.imgur.com/1xEbHJf.png)

**Comment by heminei** [comment]
Hello, 
I have published a new version. Please update the extension and check how work now :)
