### ISSUE TITLE
Option for a base source folder

### ISSUE THREAD

**Issue by dmortell** [heminei/vscode-pro-deployer#26]
Is it possible to add a configuration option to allow files in a base folder (for example /build/) to be uploaded to the target dir folder?

For example, with local folders like this:

> /build
> /build/css
> /build/js

If target dir is "/server1", they should be uploaded like this:

> /server1
> /server1/css
> /server1/js

So instead of this:
`[2023-12-17T04:22:31.130Z][INFO][SFTP] File: 'build/favicon.png' is uploaded to: '/server1/build/favicon.png'`

the upload should be like this:
`[2023-12-17T04:22:31.130Z][INFO][SFTP] File: 'build/favicon.png' is uploaded to: '/server1/favicon.png'`

**Comment by heminei** [comment]
Hi, 
 I have added two new options:

- added a new option on the target level: `baseDir`. This option allows you to set the base directory for the target. This option is useful when you want to upload files from a subdirectory of the project.
- added a new global option: `include`. This option allows you to specify which files/folders to include in the auto upload/delete. If this option is not specified, all files/folders will be included.

Please update to the last version: 2.4.1
Please if you like the extension write a review to help me: [https://marketplace.visualstudio.com/items?itemName=heminei.pro-deployer&ssr=false#review-details](url)
