### ISSUE TITLE
Upload autogenerated file

### ISSUE THREAD

**Issue by biffly** [heminei/vscode-pro-deployer#3]
Hi, this is an excellent extension, but when I save an SCSS file it compiles to its final version as CSS. The SCSS is uploaded perfectly, but the CSS that was just created or updated does not.

Could you add that option?

My apologies for my English, sorry.

**Comment by heminei** [comment]
Thanks. I will add "file watcher" options.

**Comment by biffly** [comment]
Thanks!!!!!

**Comment by heminei** [comment]
You can update the extension. Now when a file is changed will be uploaded or deleted.
