### ISSUE TITLE
How to setup so it only uploads when file/save is done by VsCode

### ISSUE THREAD

**Issue by karlitm** [heminei/vscode-pro-deployer#34]
**Is your feature request related to a problem? Please describe.**
The extension works great with both user auth and ssh-keys. Ssh-keys is what I was looking for.  But unlike the previous Extension we were using, this one uploads all the files that change regardless thet they were actually saved in VsCode.

**Describe the solution you'd like**
I understand the current automatic upload can be useful. But is there a way to deactivate it so that the only time the upload is done is when the use does CTRL-S (Save) on his file within VsCode.
Something like setting autosave=true, but autosynch=false.

Currently if I change branch in my repo, the extension automatically updates all the remote files. We don't want this to be automatic. 

**Describe alternatives you've considered**

**Additional context**

**Comment by heminei** [comment]
Hi, 
You can disable auto uploading by setting "uploadOnSave" to false. You can also manually upload by pressing "alt+u" (default shortcut).
