### ISSUE TITLE
File Watcher

### ISSUE THREAD

**Issue by dhuettner** [heminei/vscode-pro-deployer#5]
is there a possibility to deposit a file watcher?

**Comment by heminei** [comment]
Yes, the plugin has a file watcher. What do you mean? Can you explain?

**Comment by dhuettner** [comment]
> Yes, the plugin has a file watcher. What do you mean? Can you explain?
Oh it has one?! Great. Do you also have me an example of how I can / must enter this?

**Comment by heminei** [comment]
When you set these options:

**Comment by dhuettner** [comment]
Okay watcher is working. But is there also a Trigger Watcher when i work with Sass Compiler or Grunt working Task. Example: ../assetes/*(.css,js) something in this case?

**Comment by heminei** [comment]
Yes, the watcher should be working with sass compiler, grunt, etc.
