### ISSUE TITLE
add settings to the Settings > Extensions GUI

### ISSUE THREAD

**Issue by JustinWebDev** [heminei/vscode-pro-deployer#7]
After you generate and modify the config file, there is no way to get back to it to see it or modify it. The only thing I can find is to 'generate' the file again but that overwrites everything. Very frustrating.

**Comment by heminei** [comment]
Hi, for now, the extension support only local config file (.vscode/pro-deployer.json). In the future, I will think about global settings, that will be edited from settings UI.
