### ISSUE TITLE
can't upload - various errors

### ISSUE THREAD

**Issue by JustinWebDev** [heminei/vscode-pro-deployer#8]
I RMB on a file > Upload and get this error:
[PRO Deployer] My SFTP => Can't upload file: /d:/WebDev/files/thefile.txt. Details: Error: Permission denied

If I Upload to I get:
[PRO Deployer] Can't find files for uploading

I don't know where to go with either of these.  Where is the failure?

```
{
	"uploadOnSave": false,
	"autoDelete": true,
	"checkGitignore": false,
	"activeTargets": [
		"My SFTP"
	],
	"concurrency": 5,
	"ignore": [
		".git/**/*",
		".vscode/**/*"
	],
	"targets": [
		{
			"name": "My FTP",
			"type": "ftp",
			"host": "localhost",
			"port": 21,
			"user": "admin",
			"password": "123456",
			"dir": "/"
		},
		{
			"name": "My SFTP",
			"type": "sftp",
			"host": "cooldomain.org",
			"port": 22,
			"user": "myuser",
			"password": null,
			"dir": "/",
			"privateKey": "D:\\WebDev\\files\\private.ppk",
			"passphrase": "mypassphrase"
		}
	]
}
```

**Comment by heminei** [comment]
> I RMB on a file > Upload and get this error:
> [PRO Deployer] My SFTP => Can't upload file: /d:/WebDev/files/thefile.txt. Details: Error: Permission denied
Maybe the problem is on the wrong "dir" path or the user that you use doesn't have permission to write files.

> If I Upload to I get:
> [PRO Deployer] Can't find files for uploading
I can't reproduce this problem. Can you tell me are you use Workspace or just open one project (folder) in VS Code?

**Comment by JustinWebDev** [comment]
Permissions can't be the issue because in FileZilla I don't have any permission restrictions.
Is this syntax correct?  _/d:/WebDev/files/thefile.txt_
Does the config look valid?

I think it is just a project folder.

Is there a way to get detailed error information?

**Comment by heminei** [comment]
You can check the detailed log. Go to the Output tab and select PRO Deployer.
